config/routes.rb
Rails.application.routes.draw do

  get 'marquee/index'

  get 'welcome/prizes'
  get 'welcome/winners'
  get 'welcome/donators'
  get 'welcome/verify_prizes'
  get 'welcome/check_prizes'
  get 'welcome/new_prizes_stream'
  get 'welcome/revert_taken_prize'

  get 'dashboard/index'
  get 'dashboard/show_prizes'
  get 'dashboard/show_staffs'

  get 'query/index'
  get 'query/staffs'
  get 'query/staff/:id' => 'query#staff'

  get 'query/slideshow'
  get 'query/summary'
  get 'query/prizes'
  get 'query/prize/:id' => 'query#prize'
  get 'query/winner_list'
  get 'query/loser_list'
  get 'query/remaining_prizes'

  match 'register/:prize_id/:full_staff_id' => 'query#register', :via => :all
  match 'unregister/:prize_id/:full_staff_id' => 'query#unregister', :via => :all
  match 'take/:prize_id/:full_staff_id' => 'query#take', :via => :all
  match 'untake/:prize_id/:full_staff_id' => 'query#untake', :via => :all

  root 'welcome#index'

end

app/models/ability.rb
class Ability
    include CanCan::Ability

    def initialize(user)
        if user.role == 'admin'
            can :manage, :all
        else
            can :read, :all
        end
    end
end

app/models/prize.rb
class Prize
  include Mongoid::Document
  belongs_to :staff
  field :year, type: Time
  field :can_accept_prize_now, type: Mongoid::Boolean
  field :name, type: String
  field :tax, type: Integer
  field :registered_at, type: Time
  field :taken_at, type: Time
  default_scope -> { without(:year)}
  
  scope :winner_list, -> (){
    unscoped.where(:staff_id.exists => true).ne(:staff_id => nil)
  }
end

app/models/staff.rb
class Staff  
  include Mongoid::Document
  include Mongoid::Timestamps
  has_many :prizes
  field :year, type: Time
  field :department, type: String
  field :name, type: String
  field :arrival_date, type: Time
  field :trial_date, type: Time
  field :is_supervior, type: Boolean

  def prize_name
    begin
      prizes.first.name
    rescue Exception => e
      nil
    end
  end

  def donation
    min_donation = 3000
    begin
      return min_donation if self.prizes.first.tax < min_donation
      return self.prizes.first.tax
    rescue Exception => e
      return min_donation
    end
  end


  scope :by_year, ->(year) { where(:year.gte => Date.strptime( year.to_s,"%Y"), :year.lte => Date.strptime( (year+1).to_s,"%Y")) }
  default_scope -> { by_year(2016).without(:comment, :arrival_date, :created_at, :updated_at, :year) }
end

app/models/taken_prize.rb
class TakenPrize
  include Mongoid::Document
  field :prize_id, type: Integer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  http_basic_authenticate_with name: ENV["USERNAME"], password: ENV["PASSWORD"], except: :index
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end

  def show_prizes
    per_page = 50
    prizes = Prize.unscoped.sort(_id: 1).to_a.flatten
    if params.has_key? :page 
      @prizes = Kaminari.paginate_array(prizes).page(params[:page]).per(per_page)
    else
      @prizes = Kaminari.paginate_array(prizes).page(1).per(per_page)
    end
  end

  def show_staffs
  end
end

app/controllers/marquee_controller.rb
class MarqueeController < ApplicationController
  def index
  end
end

app/controllers/query_controller.rb
class QueryController < ApplicationController
  include ActionController::Live
  respond_to :json
  before_action :get_prize_and_staff, only: [:register, :unregister, :take, :untake]

  def staffs
    render json: Oj.dump( Staff.all)
  end

  def staff
    render json: Oj.dump( Staff.where(:id => params["id"]) )
  end

  def prizes
    render json: Oj.dump( Prize.all.without(:staff_id, :price) )
  end

  def prize
    render json: Oj.dump( Prize.where(:id => params["id"].to_i) )
  end

  def summary
    result = Prize.unscoped.order_by(:id.asc).collect do | prize |
      unless prize.staff_id.nil?
        staff = Staff.where(:id => prize.staff_id).first
        staff_name = staff.name
        department = staff.department
      else
        staff_name, department = nil, nil
      end
      prize.attributes.merge({staff_name: staff_name, department: department})
    end
    render json: Oj.dump( result )
  end

  def slideshow
  end

  def remaining_prizes
    render json: Oj.dump( Prize.where(:staff_id => nil).without(:staff_id, :price) )
  end

  def winner_list
    result = Prize.winner_list.order_by(:id.desc).collect do | prize |
      prize.attributes.merge({staff_name: prize.staff.name})
    end
    render json: Oj.dump(result)
  end

  def loser_list
    staffs = Staff.unscoped.all.to_a.reject do |staff|
      staff.prizes.length >= 1
    end
    render json: Oj.dump(staffs)
  end  

  def register
    response.headers["Content-Type"] = "text/javascript"
    @prize.registered_at = Time.now
    if @staff.prizes.count == 0
      @staff.prizes.push(@prize)
      @staff.save
      status = "ok"
      message = "prize registered sucessfully"
    else
      status = "fail"
      message = "can not accept more than 1 prize"
    end
    response = { status: status,
                 message: message,
                 prize: @prize, 
                 staff: @staff }
    $redis.publish('messages.create', response.to_json) if "ok" == status
    render json: Oj.dump(response)
  end

  def unregister
    @prize.registered_at = nil
    @prize.staff = nil
    @prize.save
    render json: Oj.dump({status: "ok", prize: @prize, staff: @staff})
  end

  def take
    @prize.taken_at = Time.now
    @prize.save
    render json: Oj.dump({status: "ok", prize: @prize, staff: @staff})
  end

  def untake
    @prize.taken_at = nil
    @prize.save
    render json: Oj.dump({status: "ok", prize: @prize, staff: @staff})
  end  


  private

    def get_prize_and_staff
      @prize = Prize.unscoped.where(:id => params["prize_id"].to_i).first
      @staff = Staff.unscoped.where(:id => params["full_staff_id"]).first
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  include ActionController::Live

  def index
  end
  
  def prizes
  end

  def winners
  end

  def donators
    @supervisors = Staff.unscoped.where(:is_supervior => true).order_by(:id.asc).to_a
  end
  def verify_prizes
  end

  def revert_taken_prize
  end

  def new_prizes_stream
    # http://ngauthier.com/2013/02/rails-4-sse-notify-listen.html
    begin
      response.headers.delete('Content-Length')
      response.headers['Cache-Control'] = 'no-cache'
      response.headers['Content-Type'] = 'text/event-stream'
      logger.info "New stream starting, connecting to redis"
      redis = Redis.new
      redis.subscribe('messages.create', 'heartbeat') do |on|
        on.message do |event, data|
          if event == 'messages.create'
            response.stream.write "event: #{event}\n"
            response.stream.write "data: #{data}\n\n"
          elsif event == 'heartbeat'
            response.stream.write("event: heartbeat\ndata: heartbeat\n\n")
          end
        end
      end
    rescue IOError
      logger.info "Stream closed"
    rescue ActionController::Live::ClientDisconnected
      logger.info "Client disconnected"
    ensure

      ap "close a live stream"
      redis.quit
      response.stream.close
    end
  end

  def check_prizes
    @prizes = Prize.winner_list.order_by("registered_at DESC")
  end

  private
    def sse(object, options = {})
      (options.map{|k,v| "#{k}: #{v}" } << "data: #{JSON.dump object}").join("\n") + "\n\n"
    end


end

app/helpers/application_helper.rb
module ApplicationHelper

    #    Returns the full title on a per-page basis.
    def full_title(page_title)
        base_title = "Website sandbox"
        if page_title.empty?
            base_title
        else
            "#{base_title} | #{page_title}"
        end
    end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/marquee_helper.rb
module MarqueeHelper
end

app/helpers/query_helper.rb
module QueryHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
  def get_staff_name_by_prize(prize)
    Staff.where(id: prize.staff_id).first.name
  end
end

app/views/dashboard/index.html.haml
%h1 Dashboard#index
%p Find me in app/views/dashboard/index.html.haml

app/views/dashboard/show_prizes.html.haml
%div.pagenum
  = paginate @prizes

%table.table.table-striped.table-bordered.table-hover
  %thead
    %tr
    %th.center SN
    %th.center Name
    %th.center Owner


  - @prizes.each do |prize|
    %tr
      %td.center= prize.id
      %td.center
        = prize.name
      %td.center
        - unless prize.staff.nil?
          = prize.staff.name

app/views/dashboard/show_staffs.html.haml
%h1 Dashboard#show_staffs
%p Find me in app/views/dashboard/show_staffs.html.haml

app/views/layouts/_flatlab_header_and_sidebar.html.haml
%section#container
  / header start
  %header.header.white-bg
    .sidebar-toggle-box
      .fa.fa-bars.tooltips{"data-original-title" => "Toggle Navigation", "data-placement" => "right"}
    / logo start
    %a.logo{:href => "index-2.html"}
      VIVOTEK
      %span LOTTERY
    / logo end
    #top_menu.nav.notify-row
      / notification start
      %ul.nav.top-menu
    .top-nav
      %ul.nav.pull-right.top-menu
        %li.dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            %img{:alt => "", :src => asset_path("images/vivotek-avatar.jpg"), :height => "42"}/
            %span.username 
            %b.caret
          %ul.dropdown-menu.extended.logout
            .log-arrow-up

            %li
              %a{:href => "login.html"}
                %i.fa.fa-key
                Log in
  / header end
  / sidebar start
  %aside
    #sidebar.nav-collapse
      / sidebar menu start
      %ul#nav-accordion.sidebar-menu
        %li
          %a{:href => root_path }
            %i.fa.fa-barcode
            %span 獎項登錄
        %li
          %a{:href => welcome_check_prizes_path }
            %i.fa.fa-bars
            %span 獎項複審            
        %li
          = link_to welcome_prizes_path do
            %i.fa.fa-gift
            %span 領取獎項
        %li
          %a{:href => marquee_index_path , :target => '_blank' }
            %i.fa.fa-sitemap
            %span 投影播放
        %li.sub-menu
          %a{:href => "javascript:;"}
            %i.fa.fa-glass
            %span 管理
          %ul.sub
            %li 
              = link_to "主管捐贈名單", welcome_donators_path
            %li 
              = link_to "撤銷已領取名單", welcome_revert_taken_prize_path
            %li 
              = link_to "員工清單", query_staffs_path, :target => '_blank'
            %li 
              = link_to "中獎清單", query_winner_list_path, :target => '_blank'
            %li 
              = link_to "未中獎清單", query_loser_list_path, :target => '_blank'             
            %li
              = link_to "獎項清單", query_prizes_path, :target => '_blank'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title VivoLottery
    = javascript_include_tag "application"
    = javascript_include_tag "underscore"
    = javascript_include_tag "react"
    %link{:href => asset_path("pagination/css/reset.css"), :rel => "stylesheet", :type => "text/css"}/
    %link{:href => asset_path("pagination/css/un-reset.css"), :rel => "stylesheet", :type => "text/css"}/
    %link{:href => asset_path("pagination/css/layout.css"), :rel => "stylesheet", :type => "text/css"}/
    / = stylesheet_link_tag "custom"
    = csrf_meta_tags
  %body
    = yield
    = javascript_include_tag params[:controller]
    = javascript_include_tag :slide_show, "data-turbolinks-track" => true

app/views/layouts/marquee.html.haml
!!!
%html
  %head
    %title VivoLottery
    = javascript_include_tag "application"
    = javascript_include_tag "underscore"
    = javascript_include_tag "react"
    / = stylesheet_link_tag "custom"
    = csrf_meta_tags
    %meta{:charset => "utf-8"}/
    -#%link{:href => asset_path("marquee/css/screen.css", :rel => "stylesheet")}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "A framework for easily creating beautiful presentations using HTML", :name => "description"}/
    %meta{:content => "Hakim El Hattab", :name => "author"}/
    %meta{:content => "yes", :name => "apple-mobile-web-app-capable"}/
    %meta{:content => "black-translucent", :name => "apple-mobile-web-app-status-bar-style"}/
    %meta{:content => "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui", :name => "viewport"}/
    %link{:rel => "stylesheet" , :href => asset_path("marquee/css/reveal.css" )}/
    %link#theme{:rel => "stylesheet",:href => asset_path("marquee/css/theme/black.css" )}/
    / Code syntax highlighting
    -#%link{ :rel => "stylesheet", :href => asset_path("marquee/lib/css/zenburn.css")}/
    /[if lt IE 9]
      <script src="lib/js/html5shiv.js"></script>

  %body
    .reveal
      #Marquee
        = yield
    -#%script{:src => asset_path("marquee/lib/js/head.min.js")}
    %script{:src => asset_path("marquee/js/reveal.js")}
    %script{:src => "//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"}
    -#%script{:src => asset_path("marquee/js/jquery.scrollbox.js")}
    %script{:src => asset_path("marquee/js/lodash.min.js")}
    = javascript_include_tag params[:controller]

app/views/layouts/query.html.haml
!!!
%html
  %head
    %title VivoLottery
    = javascript_include_tag "application", media: "all", "data-turbolinks-track" => true
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "underscore"
    = javascript_include_tag "react"
  %body
    = yield
    = javascript_include_tag :slide_show, "data-turbolinks-track" => true
    = javascript_include_tag :jquery_glide_min, "data-turbolinks-track" => true

app/views/layouts/welcome.html.haml
!!!
%html
  %head
    %title VivoLottery
    = javascript_include_tag "application"
    = javascript_include_tag "underscore"
    = javascript_include_tag "react"
    / = stylesheet_link_tag "custom"
    = csrf_meta_tags
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %meta{:content => "", :name => "description"}/
    %meta{:content => "Mosaddek", :name => "author"}/
    %meta{:content => "FlatLab, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina", :name => "keyword"}/
    %link{:href => "#", :rel => "s<p></p>hortcut icon"}/
    %title Form Component
    / Bootstrap core CSS
    %link{:href => asset_path("flatlab/css/bootstrap.min.css"), :rel => "stylesheet"}/
    %link{:href => asset_path("flatlab/css/bootstrap-reset.css"), :rel => "stylesheet"}/
    / external css
    %link{:href => asset_path("flatlab/assets/font-awesome/css/font-awesome.css"), :rel => "stylesheet"}/
    %link{:href => asset_path("flatlab/assets/bootstrap-datepicker/css/datepicker.css"), :rel => "stylesheet", :type => "text/css"}/
    %link{:href => asset_path("flatlab/assets/bootstrap-colorpicker/css/colorpicker.css"), :rel => "stylesheet", :type => "text/css"}/
    %link{:href => asset_path("flatlab/assets/bootstrap-daterangepicker/daterangepicker.css"), :rel => "stylesheet", :type => "text/css"}/
    / right slidebar
    %link{:href => asset_path("flatlab/css/slidebars.css"), :rel => "stylesheet"}/
    / Custom styles for this template
    %link{:href => asset_path("flatlab/css/style.css"), :rel => "stylesheet"}/
    %link{:href => asset_path("flatlab/css/style-responsive.css"), :rel => "stylesheet"}/
    %link{:href => asset_path("flatlab/css/pnotify.custom.min.css"), :media => "all", :rel => "stylesheet", :type => "text/css"}/
    = stylesheet_link_tag    params[:controller], media: "all", "data-turbolinks-track" => true    

    / HTML5 shim and Respond.js IE8 support of HTML5 tooltipss and media queries
    /[if lt IE 9]
      <script src="js/html5shiv.js"></script>
      <script src="js/respond.min.js"></script>

  %body
    = render 'layouts/flatlab_header_and_sidebar'
    %section#main-content
      = yield
    = javascript_include_tag params[:controller]
    %script{:src => asset_path("flatlab/js/jquery.js")}
    %script{:src => asset_path("flatlab/js/bootstrap.min.js")}
    %script{:src => asset_path("flatlab/js/jquery.scrollTo.min.js")}
    %script{:src => asset_path("flatlab/js/jquery.nicescroll.js"), :type => "text/javascript"}
    %script{:src => asset_path("flatlab/js/jquery-ui-1.9.2.custom.min.js")}
    %script.include{:src => asset_path("flatlab/js/jquery.dcjqaccordion.2.7.js"), :type => "text/javascript"}
    %script{:src => asset_path("flatlab/js/pnotify.custom.min.js"), :type => "text/javascript"}
    / custom switch
    %script{:src => asset_path("flatlab/js/bootstrap-switch.js")}
    / custom tagsinput
    %script{:src => asset_path("flatlab/js/jquery.tagsinput.js")}
    / custom checkbox & radio
    %script{:src => asset_path("flatlab/js/ga.js"), :type => "text/javascript"}
    %script{:src => asset_path("flatlab/assets/bootstrap-datepicker/js/bootstrap-datepicker.js"), :type => "text/javascript"}
    %script{:src => asset_path("flatlab/assets/bootstrap-daterangepicker/date.js"), :type => "text/javascript"}
    %script{:src => asset_path("flatlab/assets/bootstrap-daterangepicker/daterangepicker.js"), :type => "text/javascript"}
    %script{:src => asset_path("flatlab/assets/bootstrap-colorpicker/js/bootstrap-colorpicker.js"), :type => "text/javascript"}
    %script{:src => asset_path("flatlab/assets/ckeditor/ckeditor.js"), :type => "text/javascript"}
    %script{:src => asset_path("flatlab/assets/bootstrap-inputmask/bootstrap-inputmask.min.js"), :type => "text/javascript"}
    %script{:src => asset_path("flatlab/js/respond.min.js")}
    / right slidebar
    %script{:src => asset_path("flatlab/js/slidebars.min.js")}
    / common script for all pages
    %script{:src => asset_path("flatlab/js/common-scripts.js")}
    / script for this page
    %script{:src => asset_path("flatlab/js/form-component.js")}    
    = javascript_include_tag params[:controller], "data-turbolinks-track" => true
    = javascript_include_tag :welcome_sort_prizes, "data-turbolinks-track" => true
    = javascript_include_tag :input_prizes, "data-turbolinks-track" => true
    = javascript_include_tag :revert_taken_prize, "data-turbolinks-track" => true

app/views/query/index.html.haml
%h1 Query#index
%p Find me in app/views/query/index.html.haml

app/views/query/slideshow.html.haml
.container
  %div#Marquee

app/views/query/staffs.html.haml
%h1 Query#staffs
%p Find me in app/views/query/staffs.html.haml

app/views/welcome/check_prizes.html.haml
%section.wrapper
  .row
    .col-lg-12
      %section.panel
        %header.panel-heading
          %div#check_prizes

= javascript_include_tag :check_prizes, "data-turbolinks-track" => true

app/views/welcome/donators.html.haml
%section.wrapper
  .row
    .col-lg-12
      %section.panel
        %header.panel-heading
          %div#donators
            %table.table.table-striped
              %thead
                %tr
                  %th 部門
                  %th 主管姓名
                  %th 工號
                  %th 應捐金額
                  %th 中獎
              %tbody
                - @supervisors.each do |supervisor|
                  %tr
                    %td= supervisor.department
                    %td= supervisor.name
                    %td= supervisor.id
                    %td= supervisor.donation
                    %td= supervisor.prize_name

app/views/welcome/index.html.haml
%section.wrapper
  .row
    .col-lg-12
      %section.panel
        %header.panel-heading
          %div#input_prizes

app/views/welcome/input_prizes.html.haml
%section.wrapper
  .row
    .col-lg-12
      %section.panel
        %header.panel-heading
          %div#input_prizes

app/views/welcome/prizes.html.haml
%section.wrapper
  .row
    .col-lg-12
      %section.panel
        %header.panel-heading
          %div#searchWinner

app/views/welcome/revert_taken_prize.html.haml
%section.wrapper
  .row
    .col-lg-12
      %section.panel
        %header.panel-heading
          %div#revert_taken_prize

app/views/welcome/verify_prizes.html.haml
-#%section.wrapper
-#    .row
-#        .col-lg-12
-#            %section.panel
-#                %header.panel-heading
-#                    %div#verify_prizes
-#

app/views/welcome/winners.html.haml
%section.wrapper
  .row
    .col-lg-12
      %section.panel
        %header.panel-heading
          .row
            .col-lg-12
              %section.panel
                %header.panel-heading
                  Advanced Table
                %table.table.table-striped.table-advance.table-hover
                  %thead
                    %tr
                      %th
                        %i.fa.fa-bullhorn
                        Company
                      %th.hidden-phone
                        %i.fa.fa-question-circle
                        Descrition
                      %th
                        %i.fa.fa-bookmark
                        Profit
                      %th
                        %i.fa.fa-edit
                        Status
                      %th
                  %tbody
                    %tr
                      %td
                        %a{:href => "#"} Vector Ltd
                      %td.hidden-phone Lorem Ipsum dorolo imit
                      %td 12120.00$
                      %td
                        %span.label.label-info.label-mini Due
                      %td
                        %button.btn.btn-success.btn-xs
                          %i.fa.fa-check
                        %button.btn.btn-primary.btn-xs
                          %i.fa.fa-pencil
                        %button.btn.btn-danger.btn-xs
                          %i.fa.fa-trash-o
                    %tr
                      %td
                        %a{:href => "#"}
                          Adimin co
                      %td.hidden-phone Lorem Ipsum dorolo
                      %td 56456.00$
                      %td
                        %span.label.label-warning.label-mini Due
                      %td
                        %button.btn.btn-success.btn-xs
                          %i.fa.fa-check
                        %button.btn.btn-primary.btn-xs
                          %i.fa.fa-pencil
                        %button.btn.btn-danger.btn-xs
                          %i.fa.fa-trash-o
                    %tr
                      %td
                        %a{:href => "#"}
                          boka soka
                      %td.hidden-phone Lorem Ipsum dorolo
                      %td 14400.00$
                      %td
                        %span.label.label-success.label-mini Paid
                      %td
                        %button.btn.btn-success.btn-xs
                          %i.fa.fa-check
                        %button.btn.btn-primary.btn-xs
                          %i.fa.fa-pencil
                        %button.btn.btn-danger.btn-xs
                          %i.fa.fa-trash-o
                    %tr
                      %td
                        %a{:href => "#"}
                          salbal llb
                      %td.hidden-phone Lorem Ipsum dorolo
                      %td 2323.50$
                      %td
                        %span.label.label-danger.label-mini Paid
                      %td
                        %button.btn.btn-success.btn-xs
                          %i.fa.fa-check
                        %button.btn.btn-primary.btn-xs
                          %i.fa.fa-pencil
                        %button.btn.btn-danger.btn-xs
                          %i.fa.fa-trash-o
                    %tr
                      %td
                        %a{:href => "#"} Vector Ltd
                      %td.hidden-phone Lorem Ipsum dorolo imit
                      %td 12120.00$
                      %td
                        %span.label.label-primary.label-mini Due
                      %td
                        %button.btn.btn-success.btn-xs
                          %i.fa.fa-check
                        %button.btn.btn-primary.btn-xs
                          %i.fa.fa-pencil
                        %button.btn.btn-danger.btn-xs
                          %i.fa.fa-trash-o
                    %tr
                      %td
                        %a{:href => "#"}
                          Adimin co
                      %td.hidden-phone Lorem Ipsum dorolo
                      %td 56456.00$
                      %td
                        %span.label.label-warning.label-mini Due
                      %td
                        %button.btn.btn-success.btn-xs
                          %i.fa.fa-check
                        %button.btn.btn-primary.btn-xs
                          %i.fa.fa-pencil
                        %button.btn.btn-danger.btn-xs
                          %i.fa.fa-trash-o
                    %tr
                      %td
                        %a{:href => "#"} Vector Ltd
                      %td.hidden-phone Lorem Ipsum dorolo imit
                      %td 12120.00$
                      %td
                        %span.label.label-success.label-mini Due
                      %td
                        %button.btn.btn-success.btn-xs
                          %i.fa.fa-check
                        %button.btn.btn-primary.btn-xs
                          %i.fa.fa-pencil
                        %button.btn.btn-danger.btn-xs
                          %i.fa.fa-trash-o
                    %tr
                      %td
                        %a{:href => "#"}
                          Adimin co
                      %td.hidden-phone Lorem Ipsum dorolo
                      %td 56456.00$
                      %td
                        %span.label.label-warning.label-mini Due
                      %td
                        %button.btn.btn-success.btn-xs
                          %i.fa.fa-check
                        %button.btn.btn-primary.btn-xs
                          %i.fa.fa-pencil
                        %button.btn.btn-danger.btn-xs
                          %i.fa.fa-trash-o
                    %tr
                      %td
                        %a{:href => "#"} Vector Ltd
                      %td.hidden-phone Lorem Ipsum dorolo imit
                      %td 12120.00$
                      %td
                        %span.label.label-info.label-mini Due
                      %td
                        %button.btn.btn-success.btn-xs
                          %i.fa.fa-check
                        %button.btn.btn-primary.btn-xs
                          %i.fa.fa-pencil
                        %button.btn.btn-danger.btn-xs
                          %i.fa.fa-trash-o
                    %tr
                      %td
                        %a{:href => "#"}
                          Adimin co
                      %td.hidden-phone Lorem Ipsum dorolo
                      %td 56456.00$
                      %td
                        %span.label.label-warning.label-mini Due
                      %td
                        %button.btn.btn-success.btn-xs
                          %i.fa.fa-check
                        %button.btn.btn-primary.btn-xs
                          %i.fa.fa-pencil
                        %button.btn.btn-danger.btn-xs
                          %i.fa.fa-trash-o